[versions]
agp = "8.13.2"
kotlin = "2.4.10"
coreKtx = "1.13.1"
lifecycleRuntimeKtx = "2.6.1"
vectorDrawable = "1.2.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-vectordrawable = { module = "androidx.vectordrawable:vectordrawable", version.ref = "vectorDrawable" }
androidx-vectordrawable-animated = { module = "androidx.vectordrawable:vectordrawable-animated", version.ref = "vectorDrawable" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
