packages:
  - 'autolink/*'
  - 'bundle/*'

catalog:
  '@biomejs/biome': 2.5.3
  '@lynx-js/preact-devtools': 5.0.1-20260716151326-abdb87c
  '@lynx-js/qrcode-rsbuild-plugin': ^0.6.0
  '@lynx-js/react': ^0.123.3
  '@lynx-js/react-rsbuild-plugin': ^0.18.3
  '@lynx-js/rspeedy': ^0.16.3
  '@lynx-js/types': 4.0.0
  '@types/react': ^19.2.17
  typescript: ~6.0.3
  ws: 8.21.3
