package com.lynxapp;

import android.content.Context;

import androidx.annotation.Keep;

import com.lynx.tasm.LynxViewBuilder;
import com.lynx.tasm.library.LynxLibraryRegistry;

/**
 * App-side Lynx Autolink registry.
 *
 * Normally this class is generated by the org.lynxsdk.lynx.library-build
 * Gradle plugin; it is hand-written here because the plugin still targets
 * the pre-AGP 9 variant API. Each entry is the lynx-processor-generated
 * provider inside an autolink/* workspace library, so this list must be
 * kept in sync with the libraries in the autolink/ directory.
 */
@Keep
public final class LynxAutolinkRegistry {
    private static final String[] PROVIDERS = new String[] {
            "com.lynxapp.autolink.albumutils.LynxLibraryProviderImpl",
            "com.lynxapp.autolink.battery.LynxLibraryProviderImpl",
            "com.lynxapp.autolink.biometric.LynxLibraryProviderImpl",
            "com.lynxapp.autolink.clipboard.LynxLibraryProviderImpl",
            "com.lynxapp.autolink.deviceinfo.LynxLibraryProviderImpl",
            "com.lynxapp.autolink.display.LynxLibraryProviderImpl",
            "com.lynxapp.autolink.filesystem.LynxLibraryProviderImpl",
            "com.lynxapp.autolink.haptics.LynxLibraryProviderImpl",
            "com.lynxapp.autolink.mmkv.LynxLibraryProviderImpl",
            "com.lynxapp.autolink.router.LynxLibraryProviderImpl",
            "com.lynxapp.autolink.scanner.LynxLibraryProviderImpl",
            "com.lynxapp.autolink.screenshot.LynxLibraryProviderImpl",
            "com.lynxapp.autolink.securestorage.LynxLibraryProviderImpl",
            "com.lynxapp.autolink.sensors.LynxLibraryProviderImpl",
            "com.lynxapp.autolink.toast.LynxLibraryProviderImpl",
            "com.lynxapp.autolink.webviewbridge.LynxLibraryProviderImpl",
            "com.lynxapp.autolink.websocket.LynxLibraryProviderImpl",
    };

    private LynxAutolinkRegistry() {}

    public static void setupGlobal(Context context) {
        LynxLibraryRegistry.setupGlobal(context, PROVIDERS);
    }

    public static void setup(LynxViewBuilder builder) {
        LynxLibraryRegistry.setup(builder, PROVIDERS);
    }
}
